# Generated by Django 3.0.8 on 2021-01-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20201219_2104'),
        ('profiles', '0003_auto_20201129_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='uid',
        ),
        migrations.AddField(
            model_name='profile',
            name='content_types',
            field=models.ManyToManyField(related_name='profile_to_language_relation', to='common.Content'),
        ),
        migrations.AddField(
            model_name='profile',
            name='from_languages',
            field=models.ManyToManyField(related_name='profile_from_languages_relation', to='common.Language'),
        ),
        migrations.AddField(
            model_name='profile',
            name='to_languages',
            field=models.ManyToManyField(related_name='profile_to_language_relation', to='common.Language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
