# Generated by Django 3.0.8 on 2021-01-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210127_2010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
