# Generated by Django 3.0.8 on 2021-02-01 13:20

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210201_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='E:\\WORK\\tergum-shared-master\\0131\\tergum-shared-master\\tergum-shared-master\\staticfiles+base\\images\\profile_placeholder.png', upload_to=profiles.models.image_file_name),
        ),
    ]
