# Generated by Django 3.0.8 on 2021-02-04 11:48

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20210201_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='base\\placeholder.png', upload_to=profiles.models.image_file_name),
        ),
    ]
