# Generated by Django 3.0.8 on 2021-02-04 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20210204_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='overview',
        ),
    ]
