# Generated by Django 3.0.8 on 2021-02-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_remove_variables_content_expert_bonus'),
        ('profiles', '0010_remove_profile_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='content_types',
            field=models.ManyToManyField(blank=True, related_name='profile_to_language_relation', to='common.Content'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='from_languages',
            field=models.ManyToManyField(blank=True, related_name='profile_from_languages_relation', to='common.Language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='to_languages',
            field=models.ManyToManyField(blank=True, related_name='profile_to_language_relation', to='common.Language'),
        ),
    ]
