# Generated by Django 3.0.8 on 2020-11-20 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Job'),
        ),
        migrations.AddField(
            model_name='rate',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.JobType'),
        ),
        migrations.AddField(
            model_name='rate',
            name='source_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='common.Language'),
        ),
        migrations.AddField(
            model_name='rate',
            name='target_languages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='common.Language'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Job'),
        ),
    ]
