# Generated by Django 3.0.8 on 2020-12-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_attachment_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='job',
        ),
        migrations.AddField(
            model_name='attachment',
            name='orignal_filename',
            field=models.CharField(default='', max_length=260, unique=True),
            preserve_default=False,
        ),
    ]
