# Generated by Django 3.0.8 on 2020-12-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20201206_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='word_count',
            field=models.IntegerField(null=True),
        ),
    ]
