# Generated by Django 3.0.8 on 2020-12-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_attachment_word_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='attachmentOnly',
            field=models.BooleanField(default=False),
        ),
    ]
