# Generated by Django 3.0.8 on 2020-12-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_remove_attachment_attachmentonly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='orignal_filename',
            field=models.CharField(max_length=260),
        ),
    ]
