# Generated by Django 3.0.8 on 2020-12-10 11:36

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20201210_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=common.models.content_file_name),
        ),
    ]
