# Generated by Django 3.0.8 on 2020-12-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20201210_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='attachment_id',
            field=models.CharField(default='helo', max_length=25, unique=False),
            preserve_default=False,
        ),
    ]
