# Generated by Django 3.0.8 on 2020-12-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_attachment_attachment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment_id',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
