# Generated by Django 3.0.8 on 2020-12-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_variables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='target_languages',
            new_name='target_language',
        ),
    ]
