# Generated by Django 3.0.8 on 2020-12-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20201216_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='price',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
