# Generated by Django 3.0.8 on 2020-12-19 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0015_auto_20201216_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='job',
        ),
        migrations.AddField(
            model_name='status',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
