# Generated by Django 3.0.8 on 2021-01-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20201219_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='proofreading',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(choices=[('OP', 'Open'), ('PR', 'Progressing'), ('TR', 'Translating'), ('PF', 'Proofreading'), ('PN', 'Pending'), ('DN', 'Done')], default='PN', max_length=2),
        ),
    ]
