# Generated by Django 3.0.8 on 2021-01-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20210129_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='variables',
            name='company_share',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variables',
            name='content_expert_bonus',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variables',
            name='proofreader_share',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variables',
            name='translator_share',
            field=models.IntegerField(default=70),
            preserve_default=False,
        ),
    ]
