# Generated by Django 3.0.8 on 2021-01-31 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_auto_20210131_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variables',
            name='content_expert_bonus',
        ),
    ]
