# Generated by Django 3.0.8 on 2021-03-02 18:57

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_remove_variables_content_expert_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='variables',
            name='placeholder',
            field=models.ImageField(null=True, upload_to=common.models.placeholder_path_name),
        ),
    ]
