# Generated by Django 3.0.8 on 2021-03-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='colour',
            field=models.CharField(default='primary', max_length=30),
            preserve_default=False,
        ),
    ]
