# Generated by Django 3.0.8 on 2021-01-31 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import employee.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0019_remove_variables_content_expert_bonus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_file', models.FileField(blank=True, null=True, upload_to=employee.models.submission_file_name)),
                ('submission_filename', models.CharField(max_length=260)),
                ('submit_date', models.DateTimeField(verbose_name='Submission date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('refrence_attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Attachment')),
                ('target_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.Language')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
            },
        ),
    ]
