# Generated by Django 3.0.8 on 2021-02-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210201_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='submit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Submission date'),
        ),
    ]
