# Generated by Django 3.0.8 on 2021-02-04 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210202_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submissions',
            name='proofreading_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submissions',
            name='submission_dependency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Submissions'),
        ),
    ]
