# Generated by Django 3.0.8 on 2021-03-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
