# Generated by Django 3.0.8 on 2020-11-20 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_attachment_owner'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employeer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.JobType'),
        ),
        migrations.AddField(
            model_name='job',
            name='quality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Quality'),
        ),
        migrations.AddField(
            model_name='job',
            name='source_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_language', to='common.Language'),
        ),
        migrations.AddField(
            model_name='job',
            name='target_language',
            field=models.ManyToManyField(related_name='target_languages', to='common.Language'),
        ),
        migrations.AddField(
            model_name='contract',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Job'),
        ),
        migrations.AddField(
            model_name='contract',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
