# Generated by Django 3.0.8 on 2020-12-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20201206_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(blank=True, verbose_name='deadline for delivery'),
        ),
    ]
