# Generated by Django 3.0.8 on 2020-12-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20201206_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='word_count',
            field=models.IntegerField(blank=True),
        ),
    ]
