# Generated by Django 3.0.8 on 2020-12-06 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_attachment_owner'),
        ('services', '0006_auto_20201206_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='content',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='common.Content'),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='deadline for delivery'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='common.JobType'),
        ),
        migrations.AlterField(
            model_name='job',
            name='quality',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='common.Quality'),
        ),
        migrations.AlterField(
            model_name='job',
            name='source_language',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_language', to='common.Language'),
        ),
    ]
