# Generated by Django 3.0.8 on 2020-12-06 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_attachment_owner'),
        ('services', '0007_auto_20201206_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Content'),
        ),
    ]
