# Generated by Django 3.0.8 on 2020-12-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20201206_1343'),
        ('services', '0009_auto_20201206_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='attachments',
            field=models.ManyToManyField(related_name='job_attachments', to='common.Attachment'),
        ),
    ]
