# Generated by Django 3.0.8 on 2020-12-06 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_job_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='word_count',
        ),
    ]
