# Generated by Django 3.0.8 on 2020-12-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20201216_1423'),
        ('services', '0011_remove_job_word_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='target_language',
            field=models.ManyToManyField(related_name='target_language', to='common.Language'),
        ),
    ]
