# Generated by Django 3.0.8 on 2020-12-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20201216_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
