# Generated by Django 3.0.8 on 2020-12-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20201216_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='stripe_id',
        ),
    ]
