# Generated by Django 3.0.8 on 2020-12-19 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20201219_2104'),
        ('services', '0016_auto_20201217_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Status'),
        ),
    ]
