# Generated by Django 3.0.8 on 2021-01-29 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20210129_2050'),
        ('services', '0018_auto_20210129_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='target_language',
        ),
        migrations.AddField(
            model_name='contract',
            name='target_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_target_language', to='common.Language'),
        ),
    ]
