# Generated by Django 3.0.8 on 2021-01-30 06:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_contract_contract_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='completion_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 30, 6, 23, 0, 717626, tzinfo=utc), verbose_name='Contract completion date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='signing_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 30, 6, 23, 12, 30365, tzinfo=utc), verbose_name='Contract signed date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='signed',
            field=models.BooleanField(default=False),
        ),
    ]
