# Generated by Django 3.0.8 on 2021-01-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_auto_20210130_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Contract completion date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Contract signed date'),
        ),
    ]
