# Generated by Django 3.0.8 on 2021-01-30 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_auto_20210130_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='signed',
        ),
    ]
