# Generated by Django 3.0.8 on 2021-01-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_remove_contract_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
    ]
