# Generated by Django 3.0.8 on 2021-01-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_contract_is_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_price',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
