# Generated by Django 3.0.8 on 2021-01-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_contract_contract_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Contract completion date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signing_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Contract signed date'),
        ),
    ]
