# Generated by Django 3.0.8 on 2021-02-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_contract_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
