# Generated by Django 3.0.8 on 2021-02-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_contract_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='final',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('TR', 'Translation'), ('PF', 'Proofreading')], default='TR', max_length=2),
        ),
    ]
