# Generated by Django 3.0.8 on 2021-02-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_auto_20210219_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
