# Generated by Django 3.0.8 on 2021-02-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_auto_20210219_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='employee',
            field=models.BooleanField(default=False),
        ),
    ]
