# Generated by Django 3.0.8 on 2021-02-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_message_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='feedback',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
