# Generated by Django 3.0.8 on 2021-02-26 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0035_auto_20210226_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='chat',
            field=models.ManyToManyField(blank=True, null=True, related_name='chat_message', to='services.Message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
