# Generated by Django 3.0.8 on 2021-03-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0036_auto_20210226_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='chat',
            field=models.ManyToManyField(blank=True, related_name='chat_message', to='services.Message'),
        ),
    ]
