# Generated by Django 3.0.8 on 2021-04-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0037_auto_20210304_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('TR', 'Translation'), ('PF', 'Proofreading'), ('IN', 'Interpretation'), ('TS', 'Transcribing')], default='TR', max_length=2),
        ),
    ]
