# Generated by Django 3.0.8 on 2020-12-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stripe_keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Stripe Key',
                'verbose_name_plural': 'Stripe Keys',
            },
        ),
    ]
