# Generated by Django 3.0.8 on 2020-12-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0002_payment_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripe_keys',
            name='endpoint_secret',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
