# Generated by Django 3.0.8 on 2021-04-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0003_stripe_keys_endpoint_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripe_keys',
            name='publishable_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
